### ISSUE TITLE
feature: nodemailer based contact form

### ISSUE THREAD

**Issue by HarshArora-1205** [SandeepVashishtha/Portfolio#5]
Hi!

Is there a need of having a contact form that directly sends message to your mailbox? I can implement that using nodemailer. You have to just provide alternate google account's developer access in your deployment platform's env variables.

**Comment by SandeepVashishtha** [comment]
Hi @HarshArora-1205,

Thank you for the suggestion! Yes, having a contact form that sends messages directly to my mailbox via Nodemailer would be useful. Please go ahead with the implementation.
